### ISSUE TITLE
Docs endpoint issue

### ISSUE THREAD

**Issue by hackzaid** [miguelgrinberg/APIFairy#67]
Some basic questions here:

1. Why am I getting duplicate endpoints in docs as seen here
![image](https://user-images.githubusercontent.com/26297910/198241344-92c6edbe-c077-4550-9c69-d4bbe2916155.png)

2. How can I order the endpoints in docs the way I want, They seem scartered.

Registered endpoints
![image](https://user-images.githubusercontent.com/26297910/198241960-3f6a0738-47d4-4af2-9127-26ef95184634.png)

How they are shown in docs
![image](https://user-images.githubusercontent.com/26297910/198242158-d76baa00-8a25-48bd-bdf7-7179842f14c6.png)

Somehow, I want them to be in order in which they are registered

**Comment by miguelgrinberg** [comment]
For 1, I'm guessing you have a duplicate endpoint in your `bookings` blueprint.

For 2, you have to keep in mind that the rendering of the document is not done by APIFairy, you are using someone else's project for that. What might help is the [APIFAIRY_TAGS](https://apifairy.readthedocs.io/en/latest/intro.html#configuration) option in the configuration, which controls the order in which the blueprints are generated.

Also note that APIFairy does all its work when the decorators are invoked, which is at import time, not at registration time. You may have some luck reordering the blueprint imports. But as I said above, ultimately it is up to the documentation renderer that you use to decide which order to present the endpoints.

**Comment by hackzaid** [comment]
Thanks, all the above has been sorted. Much appreciated.

Yet another issue here, 

What do you think is causing this error when I try to revoke the access token

![image](https://user-images.githubusercontent.com/26297910/198253808-3e4fe07e-ceca-408d-85f4-9a3fafc13faa.png)

Stacktrace
```
Traceback (most recent call last):
  File "D:\Projects\......\venv\lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Projects\......\venv\lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "D:\Projects\......\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Projects\......\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Projects\......\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Projects\......\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Projects\......\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Projects\......\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Projects\......\venv\lib\site-packages\apifairy\decorators.py", line 93, in _response
    rv = f(*args, **kwargs)
  File "D:\Projects\......\venv\lib\site-packages\apifairy\decorators.py", line 34, in wrapper
    return current_app.ensure_sync(f)(*args, **kwargs)
  File "D:\Projects\......\configs\tokenguests.py", line 84, in revoke
    access_token = request.headers['Authorization'].split()[1]
  File "D:\Projects\......\venv\lib\site-packages\werkzeug\datastructures.py", line 1381, in __getitem__
    return _unicodify_header_value(self.environ[f"HTTP_{key}"])
KeyError: 'HTTP_AUTHORIZATION'
```

**Comment by miguelgrinberg** [comment]
@hackzaid that's a bug in your code:

    access_token = request.headers['Authorization'].split()[1]

There is no `Authorization` header in the request, so you get a KeyError.
